version: '3.3'

services:
  app:
    image: ${DOCKER_IMAGE:-napyouthbball_dev}
    ports:
      - 8010:80
    deploy:
      replicas: 4
      update_config:
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

  worker:
    image: ${DOCKER_IMAGE:-napyouthbball_dev}
    command: php artisan horizon
    healthcheck:
      disable: true

  redis:
    image: redis:4.0.10
    volumes:
      - type: volume
        source: napyouthbball-redis-data
        target: /data
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

volumes:
  napyouthbball-redis-data:
    external:
      true
